trigger:
- main

pool:
  name: 'MyAgentPool'

resources:
  repositories:
  - repository: terraform_azure
    type: github
    name: Lilithsudo/terraform_azure
    endpoint: Lilithsudo

steps:
- checkout: self
- checkout: terraform_azure
  persistCredentials: true

- script: |
    echo "Installer Terraform"
    curl -sL https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  displayName: 'Installer Terraform'

- script: |
    echo "Initialiser Terraform"
    terraform init
  workingDirectory: $(Build.SourcesDirectory)/terraform_azure
  displayName: 'Initialiser Terraform'

- script: |
    echo "Planifier Terraform"
    terraform plan -out=tfplan
  workingDirectory: $(Build.SourcesDirectory)/terraform_azure
  displayName: 'Planifier Terraform'

- script: |
    echo "Appliquer Terraform"
    terraform apply -auto-approve tfplan
  workingDirectory: $(Build.SourcesDirectory)/terraform_azure
  displayName: 'Appliquer Terraform'
